# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2.1

minesweeper_env: &minesweeper_env
  executor: node-lts
  working_directory: /mnt/ramdisk

minesweeper_review_context: &minesweeper_review_context
  context:
    - aws
    - minesweeper-review

just_master: &just_master
  filters:
    branches:
      only:
        - master

not_master: &not_master
  filters:
    branches:
      ignore:
        - master

executors:
  node-lts:
    docker:
      - image: circleci/node:lts

orbs:
  aws-cli: circleci/aws-cli@1.3.2

jobs:
    test:
    <<: *minesweeper_env
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

    prettier:
    <<: *minesweeper_env
      steps:
        - checkout
        - run: yarn install
        - run: yarn prettier:difference

  deploy_minesweeper_ra:
    <<: *minesweeper_env
    steps:
      - checkout
      - aws-cli/setup
      - setup_remote_docker
      - run: cd infra && yarn install --frozen-lockfile && yarn ci:deploy-review-app

  delete_old_review_apps:
    <<: *minesweeper_env
    steps:
      - checkout
      - aws-cli/setup
      - run: cd infra && yarn install --frozen-lockfile && yarn ci:destroy-old-review-apps

workflows:
  on_commit:
    jobs:
      - test
      - prettier
      - deploy_minesweeper_ra:
          <<: *minesweeper_review_context

  delete_old_review_apps:
    triggers:
      - schedule:
          cron: "19 * * * *"
          <<: *just_master

    jobs:
      - delete_old_review_apps:
          <<: *minesweeper_review_context
